server:
  port: 8003

#应用名称
spring:
  application:
    name: short-link-shop

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  # redis配置
  redis:
    database: 0
    host: localhost
    port: 16379
    timeout: 5000
    connect-timeout: 5000
    password: ${password}
    # redis连接池配置
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

  # 数据源
  shardingsphere:
    datasource:
      # 三个库
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:13306/short_link_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: ${password}
        maximum-pool-size: 50
        minimum-idle: 50
        max-lifetime: 1800000
        idle-timeout: 30000
        # 当不需要配置rules时，只是单纯的想配置数据源，则可以使用如下方式。
    rules:
      sharding:
        tables: { }   # 空表配置，表示没有分片
    props:
      sql-show: true

# minio 配置
minio:
  bucket-name: ${bucket_name}
  url: ${minio_url}
  access-key: ${minio_access_key}
  secret-key: ${minio_secret_key}



